### ISSUE TITLE
HMR with Other HOCs

### ISSUE THREAD

**Issue by DovahBrownies** [felixmosh/i18next-hmr#11]
Hi @felixmosh !

I'm trying to get HMR to work with 1st part HOCs but can't seem to get the job done.
Changing a translation will cause the HMR to trigger, but changed will not be reflected on screen, even after multiple refreshes.

*Note*
I just noticed that sometimes the changes will suddenly be reflected on screen (after a dozen reloads) but will then disappear if the page is reloaded again... Not sure what is causing this hiccup.

I cloned the `next-with-next-i18next` example and modified the `next.config` to look like so:
```
const withSass = require('@zeit/next-sass'); // ADDED THIS
const withLess = require('@zeit/next-less'); // ADDED THIS
const path = require('path');

const NextConfig = {
	publicRuntimeConfig: {
		localeSubpaths: typeof process.env.LOCALE_SUBPATHS === 'string' ? process.env.LOCALE_SUBPATHS : 'none',
	},
	webpack(config, options) {
		if (!options.isServer && config.mode === 'development') {
			const { I18NextHMRPlugin } = require('i18next-hmr/plugin');
			config.plugins.push(
				new I18NextHMRPlugin({
					localesDir: path.resolve(__dirname, 'public/static/locales'),
				}),
			);
		}

		return config;
	},
};

module.exports = withSass( // MODIFIED THIS
	withLess({
		...NextConfig,
		lessLoaderOptions: {
			javascriptEnabled: true,
		},
	}),
);
```

I had previously tried to use [next-compose-plugins](https://github.com/cyrilwanner/next-compose-plugins), nut have simplified the config file to the above configuration.

Any advice?

**Comment by felixmosh** [comment]
Hi, thank you for opening this issue, 

It is a bit difficult to help without some info.
Do you see in the browser `Client HMR has started`?
Do you similar message (`[ I18NextHMR ] Server HMR has started`) in the console?

**Comment by DovahBrownies** [comment]
Hey @felixmosh ;
Yes, both of those messages are showing; Everything looks like it's running as normal.
I mentioned that
> Changing a translation will cause the HMR to trigger

So I thought that maybe that would be clear. Sorry for the confusion!

**Comment by felixmosh** [comment]
Ok, so what doesn't works?

Can you share small repo that reproduces it?

**Comment by DovahBrownies** [comment]
@felixmosh - Apologies. It seems to be caused by my `_.app.js` code.

**Comment by felixmosh** [comment]
Glad it got solved, thank you for the update.
