### ISSUE TITLE
example with next-i18next client side translation

### ISSUE THREAD

**Issue by bryantobing12** [felixmosh/i18next-hmr#114]
**Is your feature request related to a problem? Please describe.**
I want to use client-side only translation using `next-i18next`

In `next-i18next` if we want to use client-side translation load we use this package `i18next-http-backend` and follow this [example](https://github.com/i18next/i18next-http-backend/tree/master/example/next)

I already follow that example and can manage to make it work. but every time I update the JSON translation files. it always complaining about text content does not match server renderer HTML.

![image](https://user-images.githubusercontent.com/46083126/179960605-6b1fc603-a550-4126-a410-fba7a492ade2.png)

I've added `i18next-hmr` with following this example https://github.com/felixmosh/i18next-hmr/tree/master/examples/next-with-next-i18next-v11 but the error didn't disappear

**Describe the solution you'd like**
Can update the content of JSON files without server error

**Describe alternatives you've considered**
N / A

**Additional context**
```bash
"dependencies": {
    "i18next-http-backend": "^1.4.1",
    "next": "12.2.2",
    "next-i18next": "11.2.2",
    "prop-types": "15.8.1",
    "react": "18.2.0",
    "react-dom": "18.2.0"
},
```

**Comment by felixmosh** [comment]
Can you share a repo for this.
This error raises when there are diff between what the server returns and what the client hydarates.
Looks like you have a wrong setup...

**Comment by bryantobing12** [comment]
I use this example https://github.com/felixmosh/i18next-hmr/tree/master/examples/next-with-next-i18next-v11. and the only thing I do is remove the import of `serverSideTranslations` `and getStaticProps` from [index page](https://github.com/felixmosh/i18next-hmr/blob/master/examples/next-with-next-i18next-v11/pages/index.js).

**Comment by felixmosh** [comment]
I've tried it, and looks OK to me... no errors.
But pay attention, your server side content has only keys (not translated).

**Comment by felixmosh** [comment]
Please open an issue on `next-i18next`, looks like it doesn't supports client only translations

**Comment by bryantobing12** [comment]
> BTW, why would you use Next.js if you don't render a valid content from the server?

I'm explaining it here https://github.com/i18next/i18next-http-backend/issues/92#issuecomment-1188936005

Other than my company requiring it, I mainly use `next.js` feature in my apps, like server-side requests (not all, some of my page static, and client side only too), image optimization, routing, etc.

The only thing that becomes a problem for me is how to manage translation for next.js dynamic pages/routes with `next-i18next`. 

the `next-i18next` maintainer recommends using client-side translation to solve that issue https://github.com/i18next/next-i18next/issues/1400#issuecomment-1178610620, using this example https://github.com/i18next/i18next-http-backend/tree/master/example/next. But the issue with this is I need to always restart my server in order to see changes with the translation. That's why I ended up here.

**Comment by felixmosh** [comment]
Yeah, this lib solves you the update of the app (on development) when you change translations.
Before, in Next.js, you've needed to reload the server / page.
