### ISSUE TITLE
How to integrate into Next Js 12 (next-i18next)

### ISSUE THREAD

**Issue by alextaymx** [felixmosh/i18next-hmr#115]
Is this intended to work in server side translations in next js version 12? 
![image](https://user-images.githubusercontent.com/58934562/183004937-e9746ede-0fde-4415-b08b-3f2cdbe46922.png)

**Comment by felixmosh** [comment]
Hi, I'm not sure what is the question, check the example https://github.com/felixmosh/i18next-hmr/blob/master/examples/next-with-next-i18next-v11/next.config.js

**Comment by felixmosh** [comment]
Any update?
