### ISSUE TITLE
Watch multiple i18next instances

### ISSUE THREAD

**Issue by medihack** [felixmosh/i18next-hmr#118]
**Is your feature request related to a problem? Please describe.**
Unfortunately, I have another problem. As mentioned, I am using multiple i18next instances in my app, as there are parts of the site that can have different languages (and even different resources). I have extended my "complex" example a bit to have two i18next instances: https://github.com/medihack/i18next-hmr/tree/next-complex-setup

Unfortunately, when calling `applyClientHMR` twice ([here](https://github.com/medihack/i18next-hmr/blob/efec051e5e6851387d40dafd00ca5296fe487498/examples/next-with-complex-setup/app/core/hocs/appWithSiteTranslations.js#L25) and [here](https://github.com/medihack/i18next-hmr/blob/efec051e5e6851387d40dafd00ca5296fe487498/examples/next-with-complex-setup/app/core/hocs/appWithReportTranslations.js#L25)) only the resource reloading of the second instance is triggered. The first instance is simply ignored. Is this a limitation of HMR that only one `module.hot.accept` with the same dependency ("./trigger.js") is called?

**Comment by felixmosh** [comment]
I've played around with it, and there are 2 options,
1. Allowing HMR to work with multiple i18next instances at once (the PR I've made, https://github.com/medihack/i18next-hmr/pull/4)
2. Passing the changed file to the getter function which in return you will need to decide which instance the HMR should update.

```js
const {applyClientHMR} = await import('i18next-hmr/client');
applyClientHMR(({changedFiles}) => {
  const changeFile = changedFiles[0]; // looks like 'feature2/locales/en'

  if (changeFile.startsWith('feature2')) {
    return i18nextFeature2Instance;
  }
});
```

This way, the code of the HMR remains simple, (since your use-case is supper special I don't want to add code that increases complexity for one user :])

WDYT?

**Comment by medihack** [comment]
Both options look nice. And sure, the second option would do the job (I somehow even prefer it).

**Comment by felixmosh** [comment]
would you like to try it before the publish? so I will make a branch and you will try if that works for you?

**Comment by medihack** [comment]
Sure, I can test it if you like.

**Comment by felixmosh** [comment]
I've pushed the change to `dynamic-instance` branch and made a sample usage, https://github.com/medihack/i18next-hmr/pull/5

**Comment by medihack** [comment]
Looks good. Would it be possible also to return nothing from the callback and then do nothing? That way, one could simply get informed that a language file changed and may update multiple instances manually if necessary.

**Comment by felixmosh** [comment]
Why would you want to implement things manually?

**Comment by medihack** [comment]
Because sometimes a language file changes that is used by two instances, but with option 2 (the callback option) only one instance could be updated :-( Yeah, I know ... difficult setup. And I totally understand if it's too exotic to be supported.

**Comment by felixmosh** [comment]
You will be able to update manually, and return one of the instances (hack it a bit)

**Comment by medihack** [comment]
Looks good. Thanks a lot. Closing this issue now.
