### ISSUE TITLE
Cannot resolve 'fs'

### ISSUE THREAD

**Issue by CommanderRedYT** [felixmosh/i18next-hmr#133]
**Describe the bug**
When running `next build`, I get an error about webpack not finding 'fs'.

My code looks exactly like the Next-V11 example.

![image](https://user-images.githubusercontent.com/43087936/228852551-fe0745fa-42b0-401a-8351-100b97572299.png)

**please complete the following information:**
 - OS: Linux
 - Version: 1.11.1

**Comment by felixmosh** [comment]
In `build` which is production mode, the lib should be stripped out, (it is not relevant in prod).
Make sure you have [this check ](https://github.com/felixmosh/i18next-hmr/blob/290d870a52d31a59b34aeae4bb6901ecf649b271/examples/next-with-next-i18next-v11/pages/_app.js#L4)

**Comment by CommanderRedYT** [comment]
Oh, I see my issue now! I am using Modules (import) so I skipped this. My workaround is to write `import('i18next-hmr/client').then(({ applyClientHMR }) => applyClientHMR(() => i18n));`, but I am not sure if that is correct
