### ISSUE TITLE
HMR not picking up and reflecting latest translation from API

### ISSUE THREAD

**Issue by TommyLeong** [felixmosh/i18next-hmr#147]
**Describe the bug**
Im trying to integrate HMR to achieve hot-reload on translation content that is coming from the server (API). Understand from the library and some past conversations, the hot reload should happened without page refresh.

Unfortunately, I notice as I updated some translation content in the backend. It does not reflect...
- immediately on my page (without refresh)
- even if I refresh my page (with refresh)

**_Hacky solution I did for now.._**
I set the reloadInterval to 15000ms, to get latest translation content from server, which result in creating a new i18n instance. However the user will still need to refresh the page to see my latest translation.

**To Reproduce**
I have created a repo to reproduce the issue, you may [find the repo here](https://github.com/TommyLeong/reproduce-hmr/tree/master).

**Expected behavior**
- I expect the reloadInterval shouldn't be this short of time, like what I did in my hacky solution
- HMR listen to new translation? and trigger hot reload on the frontend side.

**please complete the following information:**
 - OS: MacOS
 - Version: Version 13.0.1 (22A400]
 - Chrome Version 115.0.5790.114 (Official Build) (arm64)

**Additional context**
Rest of the package version can be found within the given repo.

**Comment by felixmosh** [comment]
Hi @TommyLeong, thank you for reporting this issue....
I've reviewed your repo, it seems that You've mixed several solutions, such as useHMR...

Since you are working with next-i18next & Next v13, I would suggest you to review the [next-with-next-i18next-v13](https://github.com/felixmosh/i18next-hmr/blob/master/examples/next-with-next-i18next-v13) example.

I've made these changes to ur repo, https://github.com/TommyLeong/reproduce-hmr/compare/master...felixmosh:fix-next-13?expand=1

For some reason I can't make a PR to your repo, so review changes in the link above :]

**Comment by TommyLeong** [comment]
Hello @felixmosh, thank you for the prompt response. 

I did not understand this change made here. Why are we pointing it to `localePath`?  Because my goal is to read from the API, not the locales that's sitting within the project.

```
localePath:
    typeof window === 'undefined'
      ? require('path').resolve('./public/locales')
      : '',
```

**Comment by felixmosh** [comment]
I didn't had the locales server on my computer :)
You can change it as you need

**Comment by TommyLeong** [comment]
The local server is actually referring to [this repo as an example](https://github.com/i18next/i18next-multiload-backend-adapter). 

It's returning payload response as such, (eg `http://localhost:8080/locales?lng=de&ns=common`)
```
{
    "de": {
        "common": {
            "missingNEW": "SERVER calling, BRAND NEW DE2"
        }
    }
}
```

### Issue im experiencing
However when I tried pointing `localePath` to local backend server, HMR throwing me following errors.

case A: `'http://localhost:8080/locales?lng={{lng}}&ns={{ns}}'`
```
Server Error
Error: Default namespace not found at http:/localhost:8080/locales?lng={{lng}}&ns={{ns}}/en/ns1.json
```

case B: `'http://localhost:8080/locales'`
```
Server Error
Error: Default namespace not found at https:/localhost:8080/locales/en/ns1.json
```

case C:  _(Slight different case)_
I also tried accepting the endpoint as per `http://localhost:8080/locales/en/ns1.json`, still it's showing me the same error
<img width="436" alt="image" src="https://github.com/felixmosh/i18next-hmr/assets/9990179/bde779a8-f76a-48c4-b88f-937d9b2b882f">



What is the payload structure HMR is looking for?

**Comment by felixmosh** [comment]
It is probably not related to this lib, you should enable CORS on your locale server since it is not on the SAME ORIGIN (postman is a server -> server request, therefore it doesn't need it)

**Comment by TommyLeong** [comment]
I don't think this is related to CORS, anyway the local server actually has CORS installed and use, line 10. 
![image](https://github.com/felixmosh/i18next-hmr/assets/9990179/4b15eacc-5dcf-41ff-bf74-a9b008771557)

I sensing the url path given is some what wrong. Why is it `https:/` instead of `https://`
<img width="743" alt="image" src="https://github.com/felixmosh/i18next-hmr/assets/9990179/652ae135-4ac5-4a35-b402-8ab0af6fb106">

FYI I tried pointing to `localhost:8080/locales` too which error end up as following
<img width="740" alt="image" src="https://github.com/felixmosh/i18next-hmr/assets/9990179/eb454ee2-6147-4c84-97e6-fccb767d7038">

**Comment by felixmosh** [comment]
This is a server side error, you need to specify the http on the server, (is that your localhost servers under **https** or **http**)? (all this not related to HMR)
If you want my help, can you provide a simple express server that will work?

**Comment by TommyLeong** [comment]
Here is the [link to the local backend repo ](https://github.com/TommyLeong/reproduce-hmr-backend). 

For postman, you can go with either..
- http://localhost:8080/locales?lng=de&ns=common
- localhost:8080/locales/en/ns1.json

**Comment by felixmosh** [comment]
Cool, I've tested this repo

1. It is weird to use HMR, since the base idea of HMR, is to watch for file changes inside the project, so how do you expect it to fetch from locales server (it is not part of the project).
2. I've managed to make it work, you need to make a change in the locales file, then go to the file in the public folder (the one that is been watched) and the lib will refetch on the **client side**,
3. Regarding server side, since Next 13, this lib is not able to trigger the same change on the server (I don't have any standard hook for this.), you should relay on `next-i18next` `reloadOnPrerender` as a server side reploading
<img width="529" alt="image" src="https://github.com/felixmosh/i18next-hmr/assets/9304194/340cae78-4d7a-4832-b8ab-9a9a51db4c30">

4. 
5. 
6. 
3. 
4. 
5.

**Comment by felixmosh** [comment]
As I've explained, server side refresh is based on the hacky `reloadOnPrerender` option of `next-i18next`, which in your case probably makes an HTTP request to the locale server, (maybe it got cached somewhere, try to add cache buster query param).

For the client side (a real HMR) you need to make a watch on your locale server folder, (I guess it is not part of your project, therefore, you can't use this lib).

As a demo, you can change your locale server file, go to the local (watched) folder, make a change to the **same** local file, you will see that the client HMR works properly.

**Comment by felixmosh** [comment]
HMR = Hot module replacement, in the case of translations, it replaces the translations in place without reloading the page at all, check the [next v12 example](https://github.com/felixmosh/i18next-hmr/tree/master/examples/next-with-next-i18next) or [any other one](https://github.com/felixmosh/i18next-hmr/tree/master/examples) to see how it works.

**Comment by TommyLeong** [comment]
> At the same time, I was trying to `next build` the project and getting following error:
> 
> ```
> ./node_modules/i18next-hmr/lib/webpack/plugin.js
> Module not found: Can't resolve 'fs'
> ```
> 
> I did this but it didn't work, can you also share how you did with yours?
> 
> ```
> use: [MultiLoadBackendAdapter, process.env.NODE_ENV !== 'production' ? new HMRPlugin({ client: true }): ''],
> ```

It's okay, I've fixed this by appending following within `next.config.js`

```
const nextConfig = {
  ...
  webpack: (config) => {
    config.resolve.fallback = { fs: false };

    return config;
  },
}
```

---
> The idea of changing locale file (.json) doesn't really work in a Production manner in my point of view, especially when building project in docker image. Or maybe I understand the concept wrongly?

Still waiting for this reply ...

**Comment by felixmosh** [comment]
> The idea of changing locale file (.json) doesn't really work in a Production manner in my point of view, especially when building project in docker image. Or maybe I understand the concept wrongly?
> 
> At the same time, I was trying to `next build` the project and getting following error:
> 
> ```
> ./node_modules/i18next-hmr/lib/webpack/plugin.js
> Module not found: Can't resolve 'fs'
> ```
> 
> I did this but it didn't work, can you also share how you did with yours?
> 
> ```
> use: [MultiLoadBackendAdapter, process.env.NODE_ENV !== 'production' ? new HMRPlugin({ client: true }): ''],
> ```

HMR as a concept is not related to production... it only suitable for **development** time as it not applied at all on prod not by Next.js nor webpack.

You should load the this lib only when NODE_ENV === 'development', this way you don't need to mock the `fs`.
The idea is that your locale files are inside public folder (which get served by Next.js by default), on prod, they deployed with the app (in a Docker container or not).
On dev mode, you (I) need to be able to modify locale files and reflect these changes on the app (just like changes in React component).

In my app, I have locales served from within public folder on **DEV** but on prod, they get served from CDN as static files.

**Comment by TommyLeong** [comment]
> HMR as a concept is not related to production... it only suitable for development time as it not applied at all on prod not by Next.js nor webpack.

Thanks again @felixmosh for your patient in explaining and demo-ing. 👍🏻
Earlier statement you posted has clarified my doubts, this library is not meant for production use. As such I'll close proceed with closing this ticket.
