### ISSUE TITLE
Translations only update on page refresh

### ISSUE THREAD

**Issue by tamj0rd2** [felixmosh/i18next-hmr#16]
Thanks for making this plugin, it's great! In my case, I'm only seeing the translations reload on page refresh. Is that the expected behaviour or could my config be wrong? Here's what I've got:

i18n.ts

```typescript
import NextI18Next from 'next-i18next'
import { IS_PROD } from './config'

const nextI18NextInstance = new NextI18Next({
  defaultLanguage: 'en',
  fallbackLng: 'en',
  fallbackNS: 'common',
  otherLanguages: ['en'],
  // ns: ['common'],
})

if (!IS_PROD) {
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { applyServerHMR } = require('i18next-hmr/server')
  applyServerHMR(nextI18NextInstance.i18n)
}

export default nextI18NextInstance

export const { appWithTranslation, withTranslation, useTranslation } = nextI18NextInstance
```

next.config.js

```javascript
const webpackConfig = (config, { isServer, defaultLoaders }) => {
  if (!isServer) {
    if (config.mode === 'development') {
      const { I18NextHMRPlugin } = require('i18next-hmr/plugin')
      config.plugins.push(new I18NextHMRPlugin({ localesDir: path.resolve(__dirname, 'public/static/locales') }))
    }
  }

  return config
}

module.exports = {
  webpack: webpackConfig,
}
```

server index.ts

```typescript
await i18n.initPromise
const app = next({ dev })
await app.prepare()

const server = express()
server.use(nextI18NextMiddleware(i18n))
server.use(getNextHandler(app.getRequestHandler()))
```

Even if this only reloads on page refresh, that's still a massive improvement over using nodemon

**Comment by felixmosh** [comment]
Thank you for reporting this bug 🙏🏼.

The whole idea is that you **won't** need to refresh the server & the client. it uses webpack's HMR in order to make it's magic.
Pay attention to the setup of the [next-i18next example](https://github.com/felixmosh/i18next-hmr/tree/master/examples/next-with-next-i18next).

You should change in your `i18n.ts` file, so it will apply **the client** HMR.
```javascript
if (process.env.NODE_ENV !== 'production') {
  const { applyClientHMR } = require('i18next-hmr');
  applyClientHMR(nextI18Next.i18n);
// -------^
}
```

And in your `server/index.ts` apply the [server HMR](https://github.com/felixmosh/i18next-hmr/blob/master/examples/next-with-next-i18next/server.js#L7-L10).

**Comment by tamj0rd2** [comment]
Well that's just amazing! Thanks for spotting that :) It's working like a charm

**Comment by felixmosh** [comment]
Good to hear :]

BTW, I didn't checked that the lib works with the latest `next-i18next@6` (which removed the need for custom server)
(I'm using a custom server at my project).

It probably does, but the serverHMR should be applied differently.
