### ISSUE TITLE
Client side hot reload doesn’t work with language codes containing a hyphen

### ISSUE THREAD

**Issue by dnbastos** [felixmosh/i18next-hmr#19]
Languages such as `pt-BR` fail to hot reload and I need to refresh the page to see the changes. 
I have to change `pt-BR` to be `pt` to work.

## Investigation
The problem starts here:
https://github.com/felixmosh/i18next-hmr/blob/master/lib/client-hmr.js#L35
```js
const currentLang = i18n.services.languageUtils.getLanguagePartFromCode(i18n.language);
```
the method `getLanguagePartFromCode('pt-BR')` returns `pt`

**Comment by felixmosh** [comment]
Hi @dnbastos, thank you for reporting this issue 🙏🏼

I'm not familiar with `lang-country` combination, are you folders structured with the same combination?

**Comment by felixmosh** [comment]
Pls try `v1.6.1`, it should work, you were right, there was no need for this language extraction

**Comment by dnbastos** [comment]
Yes, here is my folder structure:
```
locales
├── en-US
│   ├── ...
└── pt-BR
    ├── ...
```
I`m using [IETF Language Codes](https://gist.github.com/traysr/2001377)

**Comment by felixmosh** [comment]
> Yes, here is my folder structure:
> 
> ```
> locales
> ├── en-US
> │   ├── ...
> └── pt-BR
>     ├── ...
> ```
> 
> I`m using [IETF Language Codes](https://gist.github.com/traysr/2001377)

Is `v1.6.1` solved it for you? :]

**Comment by dnbastos** [comment]
Everything is working! Thanks!
