### ISSUE TITLE
Vite Build Errors

### ISSUE THREAD

**Issue by ngreenwood6** [felixmosh/i18next-hmr#198]
**Describe the bug**
I am getting the following warnings while trying to build with vite:
```
[plugin:vite:resolve] Module "path" has been externalized for browser compatibility, imported by "/tw/code/front-end/node_modules/i18next-hmr/lib/webpack/plugin.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] Module "fs" has been externalized for browser compatibility, imported by "/tw/code/front-end/node_modules/i18next-hmr/lib/webpack/plugin.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
```
As you can see from those errors it is trying to load webpack files and importing files that use `path` and `fs` even through I am using vite.

**To Reproduce**
I followed the example you have in the repository so I am pretty sure you can just run that and do a "build".

**Expected behavior**
It should not be importing these as they are not available in vite. You simply need to split out the HMR class into 2 separate files (one for webpack and one for vite so the imports don't overlap). Then just need to update it to allow the hmr plugin to be loaded respectively per platform. For example instead of `import { HMRPlugin } from 'i18next-hmr/plugin';` it could be `import { HMRPlugin } from 'i18next-hmr/vite-plugin';`

**please complete the following information:**
 - OS: ubuntu
 - Version: 3.1.3

**Comment by felixmosh** [comment]
Hi, thank you for reporting this issue.
What version of Vite are you using?

**Comment by felixmosh** [comment]
Hi, I've checked it...
This lib is ment to be used only on dev mode (when HMR is enabled).

The problem is that Vite at build time is not using the same tools as the dev.
It should not import this lib at all
```js
if (import.meta.env.MODE !== 'production') {
    const { HMRPlugin } = await import('i18next-hmr/plugin');

    instance.use(new HMRPlugin({ vite: { client: true } }));
  }
```

But it does, and then removes the entire import (weird).
I don't want to split the plugin into separate files.

I've bump Vite to latest, it doesn't show this warning :]
