### ISSUE TITLE
Support for Razzle?

### ISSUE THREAD

**Issue by jlramosr** [felixmosh/i18next-hmr#2]
I use Razzle in my React App to take advantage of SSR. I've installed this library for hot reload my locales in dev mode, but I obtain the next error:

```
Error: Cannot find module 'razzle-plugin-undefined'
Require stack:
- app\node_modules\razzle\config\runPlugin.js
- app\node_modules\razzle\config\createConfig.js
- app\node_modules\razzle\scripts\start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at runPlugin (app\node_modules\razzle\config\runPlugin.js:21:24)
    at app\node_modules\razzle\config\createConfig.js:549:16
    at Array.forEach (<anonymous>)
    at module.exports (app\node_modules\razzle\config\createConfig.js:548:13)   
    at main (app\node_modules\razzle\scripts\start.js:47:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '\\app\\node_modules\\razzle\\config\\runPlugin.js',
    '\\app\\node_modules\\razzle\\config\\createConfig.js',
    '\\app\\node_modules\\razzle\\scripts\\start.js'
  ]
}
```

And here my razzle.config.js:

```
const path = require('path');
const { I18NextHMRPlugin } = require('i18next-hmr/plugin');

module.exports = {
  modify: (defaultConfig, { target, dev }, webpack) => {
    ...
  },
  plugins: [
    new I18NextHMRPlugin({
      localesDir: path.resolve(__dirname, 'src/assets/i18n/locales'),
    }),
  ],
};

```

How I can resolve the problem? Thanks!

**Comment by felixmosh** [comment]
Hi,
I'm not familiar with razzle, there is any boilerplate or any repo that I can test it?

**Comment by felixmosh** [comment]
Thanx for this use-case, razzle works a bit differently from how this lib works.

I've managed to enable client side hmr, but the server-side requires more work.

**Comment by jlramosr** [comment]
> Thanx for this use-case, razzle works a bit differently from how this lib works.
> 
> I've managed to enable client side hmr, but the server-side requires more work.

Ok, I supposed it!

**Comment by felixmosh** [comment]
So, I've improved the lib thanx to your issue :]
Now it uses native HMR on server-side if available.

I added a [razzle-ssr example](https://github.com/felixmosh/i18next-hmr/tree/master/examples/razzle-ssr) with i18next-hmr working in server & client side.
