### ISSUE TITLE
option to hide log messages

### ISSUE THREAD

**Issue by geods3** [felixmosh/i18next-hmr#27]
**Is your feature request related to a problem? Please describe.**
it would be nice to have an option in order to hide log messages

**Comment by felixmosh** [comment]
All the logs? Client/ server? 
How would you know that everything is working?

**Comment by felixmosh** [comment]
@geods3 ?

**Comment by felixmosh** [comment]
?

**Comment by felixmosh** [comment]
Closing since the issue in inactive.
@geods3 feel free to reopen
