### ISSUE TITLE
Changes disappear after page refresh

### ISSUE THREAD

**Issue by iksent** [felixmosh/i18next-hmr#3]
Hello.

I have the next problem:

1. Using next-18next + next.js + your library setted up by example
2. Imagine I have `{ "test": "Test" }` en.json and UI which outputs "Test" string using `withTranslation` HOC.
3. I change JSON to `{ "test": "Test changed" }`
4. UI instantly changes to "Test changed" without page reloading and it's great!
5. BUT: when I reload page with F5, then I see "Test" string in the UI.

Why it could happen?

**Comment by felixmosh** [comment]
Hi, thank you for reporting this issue.

As you can see in the example, the server side hmr in next-js is based on usage of custom server.
Do you have it as well? 
Do you see this 
![image](https://user-images.githubusercontent.com/9304194/77576828-73a1cc80-6ede-11ea-8bd4-78ce0f27dd9f.png) message in the console?

**Comment by iksent** [comment]
No, I have no such message, only:

```
$ node start.js
> Using external babel configuration
[ ready ] compiled successfully
> Ready on http://localhost:3020
```

This is my server.js:

```
const express = require('express')
const next = require('next')
const nextI18NextMiddleware = require('next-i18next/middleware').default

const nextI18next = require('./src/Config/i18n/i18n')

const port = process.env.PORT || 3020
const app = next({ dev: process.env.NODE_ENV !== 'production' })
const handle = app.getRequestHandler()

if (process.env.NODE_ENV === 'development') {
  const { applyServerHMR } = require('i18next-hmr/server')
  applyServerHMR(nextI18next.i18n)
}

;(async () => {
  await app.prepare()
  const server = express()

  await nextI18next.initPromise
  server.use(nextI18NextMiddleware(nextI18next))

  server.get('*', (req, res) => {
    handle(req, res)
  })

  await server.listen(port)
  console.log(`> Ready on http://localhost:${port}`) // eslint-disable-line no-console
})()
```

and start.js:

```
require('@babel/register')({
  presets: ['@babel/preset-env'],
  ignore: ['node_modules', '.next'],
})

// Import the rest of our application.
module.exports = require('./server.js')
```

**Comment by felixmosh** [comment]
Pls check what is the value of ‘NODE_ENV’ it should be development.

**Comment by iksent** [comment]
There was `undefined` inside `server.js` for some reason...

**Comment by iksent** [comment]
Now everything is working like a charm! Thanks a lot for you package.

**Comment by felixmosh** [comment]
Thanks to your issue, I've updated all examples to use more relaxed condition.

Thank you 🙏
