### ISSUE TITLE
Support for sub namespaces?

### ISSUE THREAD

**Issue by Taraluktus** [felixmosh/i18next-hmr#6]
Hello,

We use sub namespaces (supported by I18Next) to structure our locale files.

E.g., the namespace **client/dpcm/dashboard** would result in:
./locales/de/**client/dpcm/dashboard**.json

i18next-http-backend is configured as following:
`backend: {
      loadPath: '/locales/{{lng}}/{{ns}}.json'
},`
Which works totally fine, initial resources are fetched with correct path.

Right now, i18next-hmr only looks at the last path segment to determine the namespace:
https://github.com/felixmosh/i18next-hmr/blob/d9080c291a31600f755d286b48d0e66899c51c6c/lib/plugin.js#L33

Producing the error in the screenshot:

![i18next-hmr_sub-namespaces](https://user-images.githubusercontent.com/18324525/82815081-b0675100-9e98-11ea-9b48-bd13ddb24748.PNG)

I suppose, supporting this would need i18next-hmr looking at the backend config? Or maybe it's possible to give i18next-hmr an additional option key for formatting the load path?

**Comment by felixmosh** [comment]
Thank you for opening this issue 🙏🏼
I wasn't ware / using this type of sub namespaces, so it doesn't support it **yet** :].

I will look into it later today.

**Comment by felixmosh** [comment]
Do you use is with SSR or client only?

**Comment by Taraluktus** [comment]
> Do you use it with SSR or client only?

Client only

**Comment by Taraluktus** [comment]
For completeness, the output at a fresh load:

![i18next-2](https://user-images.githubusercontent.com/18324525/82821024-9c751c80-9ea3-11ea-9754-2dfab83ee6c1.PNG)

The first 2 lines are the result of changing i18next-http-backend's backend.loadPath option to a function:
`
backend: {
  loadPath: (lngs, namespaces) => {
    console.log(lngs, namespaces);
    return '/locales/{{lng}}/{{ns}}.json';
  }
},
`

**Comment by felixmosh** [comment]
@Taraluktus can you share you i18next config?

**Comment by felixmosh** [comment]
@Taraluktus check out v1.5.0, it supports nested namespaces. 
Thank you
