### ISSUE TITLE
Problem with lazy-loaded namespaces: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Taraluktus** [felixmosh/i18next-hmr#8]
Hello,

First, thank you for supporting nested namespaces with 1.5.0, it works really well!

Occassionally, we get this error:
![i18next-hmr](https://user-images.githubusercontent.com/18324525/84003377-3b9d1800-a96a-11ea-9fa3-67a738adc734.PNG)

It sometimes happens at page reload, not really reproducible.
After that error, HMR seems to fail completely until another page reload.
(Maybe just a timing issue with a not fully initialized I18Next)

**Comment by felixmosh** [comment]
Thank you for opening this issue 🙏🏼

I need more info regarding the scenario, something that will help me to reproduce the issue.
(In my main huge project I'm using the latest version on a daily basis, didn't encounter this issue yet :])

**Comment by Taraluktus** [comment]
Thank you. I will collect more information and get back to you as soon as possible.

**Comment by felixmosh** [comment]
I tried to reproduce it, I didn't defined any namespace in the i18next config, but did required in inside `useTranslation('my-lazy-ns')`, and still it works properly.

I guess that you didn't defined the lazy namespace inside the `withTranslation / useTranslation` functions which you should.

**Comment by Taraluktus** [comment]
The lazy loaded namespace is defined in the useTranslation hook.

If no namespace would be given to withTranslation/useTranslation, I18Next uses the "defaultNS" from its init config.

**Comment by Taraluktus** [comment]
Our config:

```javascript
i18n
  .use(Backend)
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    fallbackLng: appData.defaultLanguage || 'en',
    whitelist: appData.supportedLanguages || ['en', 'de'],
    debug: process.env.NODE_ENV !== 'production',
    partialBundledLanguages: true,
    load: 'language-only',
    ns: ['common', 'topNav', 'misc', 'login', 'account'],
    defaultNS: ['common'],
    keySeparator: '....',
    backend: {
      loadPath: '/locales/{{lng}}/{{ns}}.json'
    },
    detection: {
      order: ['localStorage', 'navigator', 'querystring', 'cookie', 'htmlTag']
    },
    interpolation: {
      escapeValue: false // not needed for react as it escapes by default
    },
    react: {
      transKeepBasicHtmlNodesFor: ['br', 'strong', 'i', 'b', 'pre', 'em', 'small']
    }
  });
```

**Comment by felixmosh** [comment]
Check this example (react-i18next), https://github.com/felixmosh/i18next-hmr/tree/lazy-nested-bug
It has a `ns` config + lazy loaded using `withTranslation`, it works

**Comment by felixmosh** [comment]
@Taraluktus any update?

**Comment by Taraluktus** [comment]
Sorry, I was not able to create a Codesandbox with working HMR ("WDS: Disconnected" all the time).

As I said, we always give a namespace at useTranslation call, so that's not the issue.
The example does not really reflect our issue. The problem only occurs for namespaces that are **not** given at "ns" option in i18next init, and that are **not yet** loaded by i18next-http-backend in combination with i18next's "partialBundledLanguages" option (lazy loading).

It's probably not neccessary for i18next-hmr to support that use case.
But it would be nice if utils.js/extractLangAndNS would be more failsafe, as you did in your example.

**Comment by felixmosh** [comment]
Will it a trouble for you to update my example branch with something that mimicking your scenario properly?

**Comment by Taraluktus** [comment]
Of course, will update the example branch in the next few days (long weekend here).

Maybe i18next-hmr should just ignore/skip, if extractLangAndNS does not get valid values (changedFile could also be undefined on Windows, for example!). In the lazy load case, that would totally make sense since the .json wasn't loaded before by i18next, so no need to "reload" it.

**Comment by felixmosh** [comment]
Ha, I didn't thought about a scenario that you are editing a json file which is not used inside the current page, in this scenario, HMR will throw but it should not.

Is this your case?

**Comment by Taraluktus** [comment]
Yes! Sorry, I should have been more precise ;-)

**Comment by felixmosh** [comment]
Cool, will fix this. thank you 🙏🏼
