### ISSUE TITLE
Translation changes not reflected with custom `localePath`

### ISSUE THREAD

**Issue by DovahBrownies** [felixmosh/i18next-hmr#9]
### Steps to reproduce:
1 - Clone: `https://github.com/felixmosh/i18next-hmr/tree/master/examples/next-with-next-i18next`
2 - Move `/locales` folder from `/public/static` to the root of the project (`~`)
3 - Change the `localesDir` in `~/next.config.js`:
```
new I18NextHMRPlugin({
     localesDir: path.resolve(__dirname, 'locales') // was: 'public/static/locales'
})
```
4 - Add `localePath` to `next-i18next` instance config:
```
const nextI18Next = new NextI18Next({
     localePath: 'locales', // Add this
     otherLanguages: ['de'],
     localeSubpaths: localeSubpathVariations[localeSubpaths],
});
```

### Problem:
Changing any of the translations in `~/locales` will trigger an HMR reload, but the change will not be seen on-screen. Even after reloading the browser. Server needs to be fully stopped and re-started.

**Comment by felixmosh** [comment]
Do you see any errors in the console / browser?

**Comment by DovahBrownies** [comment]
Thanks for the answer, @felixmosh .
I did not see any obvious errors or issues when doing this. Everything seemed like it was (or should have been) working fine.

I did **not** add any extensions or libraries to serve the `~/locales` folder.

Any advice regarding this?

*Note:*
_In the cloned repo (without any changes), edited translations will not change on screen until a refresh is done._

**Comment by felixmosh** [comment]
Next's default config serving all files that are under `public` folder, there is no good reason to move it out side.

I've just checked the example again, it works properly.
![LxXJKn37Aw](https://user-images.githubusercontent.com/9304194/84399357-6b1d8000-ac09-11ea-9c0c-ee9a49a88f83.gif)

**Comment by DovahBrownies** [comment]
I can't tell where the `common.json` file is.
But like I said; it'll work perfectly under `/public`.
I'll reconsider moving all the translations to `/public`, after some thinking, and I'll probably close this issue afterwards. Thanks.

**Comment by felixmosh** [comment]
Cool, glad to help :]

**Comment by felixmosh** [comment]
Did it solved?

**Comment by DovahBrownies** [comment]
Yes I've decided to put the translations in `/public` for now. I'll update this thread with any new info if I decide to do more digging. Thanks a bunch, @felixmosh !
